---
stages:
  - test

molecule:
  stage: test
  image: $CI_REGISTRY/docker/molecule
  script:
    - git config --global
      url."$(expr match "$CI_REPOSITORY_URL" '\(.\+://[^/]*\)')/".insteadOf
      "git@$(expr match "$CI_REPOSITORY_URL" '.\+://.\+@\([^/]*\)'):"
    - molecule --version
    - molecule test
