---

- name: Install docker-compose required packages
  become: true
  ansible.builtin.package:
    name: "{{ docker_compose_required_packages }}"
    state: present
  tags:
    - install
    - install-docker-compose

- name: Download docker-compose static binary
  become: false
  run_once: true
  delegate_to: localhost
  register: _download_docker_compose
  until: _download_docker_compose is succeeded
  retries: 15
  delay: 1
  ansible.builtin.uri:
    url: "{{ docker_compose_url }}"
    dest: "{{ playbook_dir }}/files/{{ docker_compose_arch }}-docker-compose-{{ docker_compose_release }}"
    creates: "{{ playbook_dir }}/files/{{ docker_compose_arch }}-docker-compose-{{ docker_compose_release }}"
    mode: "0644"
    status_code:
      - 200
      - 304
  tags:
    - install
    - install-docker-compose
    - tarball-docker-compose-download
    - tarball-download

- name: Create a directory for docker if it does not exist
  become: true
  ansible.builtin.file:
    path: /opt/docker
    state: directory
    mode: "0755"
    owner: root
    group: "0"
  tags:
    - install
    - install-docker-compose

- name: Check docker-compose installed version
  ansible.builtin.stat:
    path: /opt/docker/COMPOSE_INSTALLED.VERSION
  register: _docker_compose_installed_version
  tags:
    - install
    - install-docker-compose

- name: Read /opt/docker/COMPOSE_INSTALLED.VERSION file
  ansible.builtin.slurp:
    src: /opt/docker/COMPOSE_INSTALLED.VERSION
  register: _docker_compose_installed_version_string
  when: _docker_compose_installed_version.stat.exists
  tags:
    - install
    - install-docker-compose

- name: Install docker-compose
  when: >-
    not _docker_compose_installed_version.stat.exists
    or ((_docker_compose_installed_version_string.content | default('') | b64decode)
    != ('{docker_compose_arch}-{docker_compose_release}'.format(**vars)))
  block:
    - name: Copy docker-compose binary
      diff: false
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/{{ docker_compose_arch }}-docker-compose-{{ docker_compose_release }}"
        dest: /opt/docker/docker-compose
        mode: "0755"
        owner: root
        group: "0"
      tags:
        - install
        - install-docker-compose
    - name: Ensure alternatives links is exists for docker-compose
      become: true
      community.general.alternatives:
        name: docker-compose
        link: /usr/local/bin/docker-compose
        path: /opt/docker/docker-compose
        state: "{{ (docker_compose_install | bool) | ternary('present', 'absent') }}"
      tags:
        - install
        - install-docker-compose
    - name: Create a directory for docker cli-plugins if it does not exist
      become: true
      ansible.builtin.file:
        path: /usr/local/lib/docker/cli-plugins/
        state: directory
        mode: "0755"
        owner: root
        group: "0"
      when:
        - docker_compose_plugin_install | bool
      tags:
        - install
        - install-docker-compose
    - name: Ensure alternatives links is exists for docker compose plugin
      become: true
      community.general.alternatives:
        name: docker-compose-cli-plugin
        link: /usr/local/lib/docker/cli-plugins/docker-compose
        path: /opt/docker/docker-compose
        state: "{{ (docker_compose_plugin_install | bool) | ternary('present', 'absent') }}"
      tags:
        - install
        - install-docker-compose
    - name: Save /opt/docker/COMPOSE_INSTALLED.VERSION file
      become: true
      ansible.builtin.copy:
        content: "{{ docker_compose_arch }}-{{ docker_compose_release }}"
        dest: /opt/docker/COMPOSE_INSTALLED.VERSION
        mode: "0644"
        owner: root
        group: "0"
      tags:
        - install
        - install-docker-compose
