---

- name: Install docker-compose required packages
  become: true
  ansible.builtin.package:
    name: "{{ docker_compose_required_packages }}"
    state: present
  tags:
    - install

- name: Download docker-compose static binary
  become: false
  run_once: true
  delegate_to: localhost
  register: _download_docker_compose
  until: _download_docker_compose is succeeded
  retries: 15
  delay: 1
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ playbook_dir }}/files/{{ docker_compose_arch }}-docker-compose-{{ docker_compose_release }}"
    mode: 0644

- name: Create a directory for docker if it does not exist
  become: true
  ansible.builtin.file:
    path: /opt/docker
    state: directory
    mode: 0755

- name: Check docker-compose installed version
  ansible.builtin.stat:
    path: /opt/docker/COMPOSE_INSTALLED.VERSION
  register: _docker_compose_installed_version

- name: Read /opt/docker/COMPOSE_INSTALLED.VERSION file
  ansible.builtin.slurp:
    src: /opt/docker/COMPOSE_INSTALLED.VERSION
  register: _docker_compose_installed_version_string
  when: _docker_compose_installed_version.stat.exists

- name: Install docker-compose
  become: true
  when: not _docker_compose_installed_version.stat.exists
      or ((_docker_compose_installed_version_string.content | default('') | b64decode) != ('{docker_compose_arch}-{docker_compose_release}'.format(**vars)))
  block:
    - name: Save /opt/docker/COMPOSE_INSTALLED.VERSION file
      ansible.builtin.copy:
        content: "{{ docker_compose_arch }}-{{ docker_compose_release }}"
        dest: /opt/docker/COMPOSE_INSTALLED.VERSION
        mode: 0644
    - name: Copy docker-compose binary
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/{{ docker_compose_arch }}-docker-compose-{{ docker_compose_release }}"
        dest: /opt/docker/docker-compose
        mode: 0755

- name: Ensure alternatives links is exists for docker-compose
  become: true
  community.general.alternatives:
    name: docker-compose
    link: /usr/local/bin/docker-compose
    path: /opt/docker/docker-compose
