---

- name: Install required packages | {{ _distribution_string }}
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.apt:
    name: "{{ docker_required_packages | union(_required_packages) }}"
    state: present
    update_cache: true
    install_recommends: false
  vars:
    _installation_type_required_packages: >-
      {{ q('ansible.builtin.vars', 'docker_{docker_installation_type}_required_packages'.format(**vars), default=[]) }}
    _required_packages: >-
      {{ docker_required_packages_extra | union(*_installation_type_required_packages) }}
  tags:
    - install
    - install-docker

- name: Install packages | {{ _distribution_string }}
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.apt:
    state: present
    name: "{{ docker_packages | union(_packages) }}"
    update_cache: true
    install_recommends: false
  vars:
    _packages: >-
      {{ docker_packages_extra }}
  tags:
    - install
    - install-docker

- name: "Include tasks {{ docker_installation_type }}"
  ansible.builtin.include_tasks: "{{ _filename }}"
  vars:
    _filename: "{{ lookup('first_found', _first_found_list, errors='ignore') }}"
    _filename_format: "{{ 'install_{docker_installation_type}_\\1.yml'.format(**vars) }}"
    _first_found_list: >-
      {{ docker_first_found_list | map('regex_replace', '(.+)', _filename_format) | list }}
  when:
    - _filename is exists
  tags:
    - install
    - install-docker
