---

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Systemctl restart-docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Systemctl restart-containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted
