---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - &platform-basic
    name: molecule-docker-fc40-package-${CI_JOB_ID:-1}
    image: fedora:40
    volumes:
      - /var/lib/docker
      - /lib/modules:/lib/modules:ro
    keep_volumes: false
    tty: true
    tmpfs:
      - /run
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    privileged: true  # For dockerd
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For dockerd
      - SYS_MODULE  # For dockerd and modprobe
      - SYS_RESOURCE  # For dockerd oom_score_adj
    security_opts:
      - apparmor=unconfined
      - seccomp=unconfined
    groups:
      - docker_package
  - &platform-tarball
    <<: *platform-basic
    name: molecule-docker-fc40-tarball-${CI_JOB_ID:-1}
    groups:
      - docker_tarball
  - <<: *platform-basic
    name: molecule-docker-deb12-package-${CI_JOB_ID:-1}
    image: debian:12
  - <<: *platform-tarball
    name: molecule-docker-deb12-tarball-${CI_JOB_ID:-1}
    image: debian:12
  - <<: *platform-basic
    name: molecule-docker-ubuntu22.04-package-${CI_JOB_ID:-1}
    image: ubuntu:22.04
  - <<: *platform-tarball
    name: molecule-docker-ubuntu22.04-tarball-${CI_JOB_ID:-1}
    image: ubuntu:22.04

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callbacks_enabled: profile_roles,profile_tasks,timer
    diff:
      always: true
verifier:
  name: ansible
