---

- name: Check docker is started and enabled at boot
  become: true
  check_mode: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  register: docker_service_status

- name: Test docker service is started and enabled at boot
  ansible.builtin.assert:
    that:
      - not docker_service_status.changed

- name: Get current docker version
  changed_when: false
  ansible.builtin.command: >-
    {%- raw -%}
    docker version -f
    '{
      "client": "{{.Client.Version}}",
      "server": "{{.Server.Version}}"
    }'{%- endraw -%}
  register: _docker_info

- name: Check docker installed version
  ansible.builtin.include_tasks:
    file: "docker_{{ docker_installation_type }}.yml"

- name: Check docker-compose installed version
  ansible.builtin.include_tasks:
    file: "docker_compose_{{ docker_installation_type }}.yml"
  when:
    - docker_compose_install | bool or docker_installation_type == 'package'
